### ISSUE TITLE
Implement a logging system

### ISSUE THREAD

**Issue by AnonGuy** [CyberDiscovery/cyberdisc-bot#114]
This could be done with Python's builtin `logging` library, `loguru` or `sentry`, but preferrably a logging system implemented from scratch (subclassed from `logging.Logger`).

It should be able to send all log messages to a channel ID specified in `constants.py`.

**Comment by jos-b** [comment]
Sentry may be useful for error reporting but it isn't a great logging solution. It's mainly for exception reporting and management.

**Comment by jos-b** [comment]
Can handle this issue 👌. I'm going to try going with normal `logging` first and if that fails (all that async trickery) then I'll move onto trying `loguru`.
