### ISSUE TITLE
Rewrite a line of code to be more readable

### ISSUE THREAD

**Issue by joker314** [CyberDiscovery/cyberdisc-bot#132]
:bulb: This issue has been written for people who haven't contributed to this repository before. It's a "**good first issue**"

<hr>

# :heavy_check_mark:  The task

In #131, a really useful feature was added to a joke command called `:flag`. It added the string `"||"` to either side of the flag.

The flag is generated by calling the `generatebase64` function with some arguments. We want to rewrite the line which determines the output so that it uses [f-strings](https://docs.python.org/3/whatsnew/3.6.html#whatsnew36-pep498).

https://github.com/CyberDiscovery/cyberdisc-bot/blob/c8b262eda5207e7a51d369853d6ed7e62ca9fa9b/bot/cogs/cyber.py#L143

We want to do this in two parts
 - store the result of `generatebase64` in a variable, probably called `flag`
 - then, using f-strings, insert the flag without using the concatenation (`+`) operator into the `content` variable

The reason we want to do it in this way is that it's easier to read the function call if it's just on one line, and f-strings are considered better style because they are more concise. Remember that `await` is part of the function call.

# :file_folder:  Files that need to be modified and helpful resources
- [`/src/bot/cogs/cyber.py`](https://github.com/CyberDiscovery/cyberdisc-bot/blob/master/bot/cogs/cyber.py#L143) - the file that needs to be changed (see line 143)
- [How to run and test the bot](https://github.com/CyberDiscovery/cyberdisc-bot/blob/master/README.md)
- [Contribution guidelines (code of conduct)](https://github.com/CyberDiscovery/cyberdisc-bot/blob/master/CODE_OF_CONDUCT.md)

You'll need to:
 - Fork this repository so that you get a copy under your own personal GitHub account that you can change.
 - Optional: create a separate _branch_ for your changes
 - Make your changes and commit them
    - You can do this in GitHub if you want
     - or, you can use a program called "Git" if you can, and then push your changes to GitHub
  - Create a pull request

We'll then review your pull request and give you feedback.

**If you need any help, please ask us. We're very friendly.**

**Comment by swedg** [comment]
uh, you could've just done a PR? (also templates are cool but this is a bit much)

**Comment by fractalpenguin** [comment]
This is extremely verbose, for a very minor issue. There's no need to hand-hold contributors through every single step of the pull request process, given that there are already resources online. Feel free to produce a set of instructions separately though.

**Comment by AnonGuy** [comment]
Whilst this is a good writeup, and you've clearly put a lot of work into it, I would like to note the fact that our community is capable of making contributions to the bot that are a lot more useful than adding a couple of characters, even from a complete beginner. This is the sort of issue that would be addressed in the Pull Request that the feature was implemented in, and given that you brought this issue up *late* in the comments of a *closed* Pull Request, I am closing this issue.

Besides, there are many other resources that beginners can take advantage of, such as the [GitHub Learning Lab](https://lab.github.com/), which is a lot more useful than manipulating a couple of characters to address a non-issue. We are accepting of of any skill level, but I personally don't think this is the best route to learning. Feel free to make an issue for a potential feature that you believe would be useful to the community.
