### ISSUE TITLE
Bot-generated images added to staging area

### ISSUE THREAD

**Issue by fractalpenguin** [CyberDiscovery/cyberdisc-bot#134]
**Describe the bug**
The bot-generated images appear on git status.

**To Reproduce**
1. Use a create-text-image based command e.g ":jibhat"

**Expected behavior**
The image added should not be added to the staging area.

**Additional context**
This can be fixed by adding the generated images to the .gitignore

**Comment by swedg** [comment]
Whoops that was an accident my bad

**Comment by AnonGuy** [comment]
A solution to this could be saving the images to an `io.BytesIO` object, rather than saving them to disk.
