### ISSUE TITLE
Embeds for #readme

### ISSUE THREAD

**Issue by teamshortcut** [CyberDiscovery/cyberdisc-bot#147]
At the moment, #readme (in the server) is slightly hard to read, and spread across different messages. It would be nice if we could use the bot to resend this content with some nicer looking embeds. This would allow the content to be split up slightly more, and to have some fancy colours in there for readibility.

It would be heplful to have the content for this stored somewhere where admins are able to edit it, and some way (perhaps an admin-only) command to purge the current content of #readme and resend the updated text.

This text should include everything currently in there, perhaps slightly reformatted. This includes the rules of the server, clarifications, and explanations of our roles. This may also be a good opportunity to add explanations of a few of the channels, though this isn't exactly important.

**Comment by AnonGuy** [comment]
If someone's going to implement this, we'll need a formatted and consistent set of rules, each with a different category for each embed.

**Comment by thebeanogamer** [comment]
Resolved in #159
