### ISSUE TITLE
Moving to a new CI platform

### ISSUE THREAD

**Issue by AnonGuy** [CyberDiscovery/cyberdisc-bot#167]
We've already had some internal discussion on possible CI platforms that we can use, but I'm making this issue so we can get some public discussion.

After [Travis' recent acquisition and layoffs](https://news.ycombinator.com/item?id=18978251), some of our bot contributors have expressed concerns on whether continuing to use the service is a safe bet. For that reason, we're considering a move to a different CI platform. Some solutions we've discussed are:

* **[Azure Pipelines](https://azure.microsoft.com/en-us/services/devops/pipelines/)**
* **[Circle CI](https://circleci.com/)**

Some things we need to do to complete the migration:
- [ ] Choose a platform
- [ ] Make a PR for the move
- [ ] Create the configuration file/s
- [ ] Ensure @swedg has access to the service and has added the required environment variables

**Comment by thebeanogamer** [comment]
Resolved by #158
