### ISSUE TITLE
Quotes command produces horrific pingspam

### ISSUE THREAD

**Issue by thebeanogamer** [CyberDiscovery/cyberdisc-bot#186]
**Describe the bug**
When the bot displays a quote that isn't an embed, all the pings within the message function. This leads to very annoying ping spam.

**To Reproduce**
1. Use command ':quotes' until you get a quote like the one below
![image](https://user-images.githubusercontent.com/3729048/55970218-0ff3a480-5c77-11e9-9096-6003d80bc400.png)
2. Wait for the user who has just been pinged to scream at you

(For when I come to look at this in 20 years, I'd encourage my future self to look at neither my profile, nor the quote itself)

**Expected behavior**
The bot should convert any messages which are not already embeds into embeds, therein breaking the pings.

**Comment by AnonGuy** [comment]
Would it be easier to just call [Message.clean_content()](https://rapptz.github.io/discord.py/docs/api.html?highlight=clean#discord.Message.clean_content)?

**Comment by AnonGuy** [comment]
Would it be easier to just call [Message.clean_content()](https://rapptz.github.io/discord.py/docs/api.html?highlight=clean#discord.Message.clean_content)?

**Comment by AnonGuy** [comment]
Would it be easier to just call [Message.clean_content()](https://rapptz.github.io/discord.py/docs/api.html?highlight=clean#discord.Message.clean_content)?

**Comment by AnonGuy** [comment]
Would it be easier to just call [Message.clean_content()](https://rapptz.github.io/discord.py/docs/api.html?highlight=clean#discord.Message.clean_content)?

**Comment by AnonGuy** [comment]
Would it be easier to just call [Message.clean_content()](https://rapptz.github.io/discord.py/docs/api.html?highlight=clean#discord.Message.clean_content)?

**Comment by thebeanogamer** [comment]
That would probably also work.

**Comment by AnonGuy** [comment]
Wouldn't it be easier to call [`Message.clean_content`](https://rapptz.github.io/discord.py/docs/api.html?highlight=clean#discord.Message.clean_content)?

**Comment by thebeanogamer** [comment]
It probably would be.

Whilst embeds would look nicer, that would solve the problem in the short term.

**Comment by AnonGuy** [comment]
Yeah that's fair

**Comment by thebeanogamer** [comment]
Resolved by #197
