### ISSUE TITLE
A simpler demployment process

### ISSUE THREAD

**Issue by AvrooVulcan** [CyberDiscovery/cyberdisc-bot#193]
It has come to my attention that you need to be running an absurd amount of external resources such as pyenv and poetry to even touch this resource. It's practically impossible for someone who isn't running a linux distribution to contribute, without spending hours setting it up.

**Comment by maishams** [comment]
#stoptheOSism #banbeano #makemaisharoot

**Comment by fractalpenguin** [comment]
There is a very clear setup guide in the readme. Furthermore, you do not actually NEED to use poetry or pyenv locally in order to run the bot, and can opt to use any dependency management method of your choice.
