### ISSUE TITLE
:react command silently omits letters if no emoji are available

### ISSUE THREAD

**Issue by picapi** [CyberDiscovery/cyberdisc-bot#209]
If a user uses the react command, but there are insufficient emoji to represent each letter requested, the command will omit letters once the pool is exhausted. As a result, in the worst-case scenario, a phrase could theoretically cause another phrase to be displayed, one which the author may not have intended. 
An example; you can see that a couple of I's could not be added, but the rest of the message is reacted.

![image](https://user-images.githubusercontent.com/7061144/56457259-c3435400-636f-11e9-9c79-58ecfbc53cc9.png)

It may be better if the bot was to provide some sort of feedback, or otherwise refrain from displaying behaviour which is not intended by the user of the command.

**Comment by theforkbomber** [comment]
```py
def convert_emoji(message: str) -> List[str]:
    """Convert a string to a list of emojis."""
    emoji_trans = list(map(iter, EMOJI_LETTERS))
    # Enumerate characters in the message

    emojified = []

    for character in message:
        index = ascii_lowercase.find(character)
        if index == -1:
            continue
        # Yield the next iteration of the letter
        try:
            emojified.append(next(emoji_trans[index]))
        except StopIteration:
            return ['Error']

    return emojified


async def emojify(message: Message, string: str):
    """Convert a string to emojis, and add those emojis to a message."""
    if convert_emoji(string.lower()) == ['Error']:
        await message.channel.send('Too many of the same character for convert_emoji.')
        return
    for emoji in convert_emoji(string.lower()):
        if emoji is not None:
            await message.add_reaction(emoji)
```
"It may be better if the bot was to provide some sort of feedback, or otherwise refrain from displaying behaviour which is not intended by the user of the command." This only achieves the latter.

**Comment by NilsIrl** [comment]
Instead of omitting the letter, the bot could place a random emoji instead.

Or new emojis could be added to the server which contain letters.

The bot could also dynamically add emojis to the server depending on the needed letter.

**Comment by JoshHeng** [comment]
I don't think new emojis should be added because Discord has an emoji limit.

I think just display an error message
