### ISSUE TITLE
Quote Feature Ideas List

### ISSUE THREAD

**Issue by teamshortcut** [CyberDiscovery/cyberdisc-bot#26]
-If message has 5 pin reactions, automatically add to #quotes (or pin to current channel)
-Use `!quote` to get a random message from #quotes
-Use `!quote [user]` to get a random message from #quotes from a specific user

**Comment by teamshortcut** [comment]
@st1ngr3y @dwouca @teamshortcut

**Comment by teamshortcut** [comment]
-(potentially) A "this time last year" feature

**Comment by fractalpenguin** [comment]
Take discussion to #7
