### ISSUE TITLE
GCI Invite Link on mention of GCI

### ISSUE THREAD

**Issue by FreddieN** [CyberDiscovery/cyberdisc-bot#266]
**Is your feature request related to a problem? Please describe.**
As we draw closer to the start of GCI, many CD users continue to question what GCI is and how they can get involved.

**Describe the solution you'd like**
On a mention of GCI, the bot should give a brief explanation of GCI and a link to the official CD linked GCI server. This should be on a channel cooldown to avoid the message being spammed on every mention of GCI. I would be willing to write this if you approved.

**Describe alternatives you've considered**
Similar to the FAQ part of the bot we could instead add the questions like 'What is GCI?' but this may not catch everything. 

**Additional context**
N/a

**Comment by thebeanogamer** [comment]
Closed as stale
