### ISSUE TITLE
Integrated Administration Functionality

### ISSUE THREAD

**Issue by thebeanogamer** [CyberDiscovery/cyberdisc-bot#294]
So I know this has come up before ~and I've been against it~, but I think that the point has come where we have started to grow beyond what Dyno can offer, and a plan has started to be ~feature creeped~ discussed in #staff. We'd be interested to see community feedback, suggestions, and cries of "You'll never actually build it" whilst uncomfortably glancing at the activities website...

Suggestions this far (not all from me, I'm just collating them):
* Discord OAuth
* Role based access control
* Case tracking
* Staff voting on cases and the bot taking moderation access as appropriate
* Web interface for both administration and users wanting to view ongoing moderations
* Allow moderators to attach notes to users
* Bot posts moderation actions as they are taken
* Modmail

Obviously, some of these ideas are better than others, and some are more doable than others, but we'd be interested to see any further ideas or opinions on the ones suggested here!

**Comment by NicholasG04** [comment]
All of them sound like a waste of time to me. Just scrap Dyno, get Gaius Cicereius, don't worry about a shitty web panel it's a waste of time. No voting should be necessary on 'cases' since in experiences I've seen action has to be taken there and then.

**Comment by thebeanogamer** [comment]
The point of this is less replacing automod, it's more to focus on situations where actual humans are required to make choices.

**Comment by NicholasG04** [comment]
I don't see the point of an overly complex webapp for a simple task. What the server really needs imo are punishments for warnings and better guidelines on when to warn people. All of this stuff about cases really seems ott for me

**Comment by thebeanogamer** [comment]
Oh, I agree, it's overkill as hell, but equally, overkill as hell is kinda our thing. Plus, standardising moderation would be assisted by this, as it provides greater visability into cases, as well as presets which can be used by moderators.

**Comment by Sh3llcod3** [comment]
So I think I was writing something for this, but this is definitely more defined as to what it needs...

**Comment by lightspeedana** [comment]
Here's a lovely list of automod features we should be able to add ourselves:

- Delete banned words, with an automute 
- Delete and warn for fast message spam
- Delete and warn for invite links 
- Delete and warn for mass mentions, followed by automute (max count 8)

There's also selfbot detection, but I don't know if that's implementable and will leave that up to you. 

Automute time is 15 minutes, and you need 3 violations of the above to receive one (unless stated otherwise). Link cooldown needs to be 60 seconds. 

I hope this is all implementable and clear 😄 Happy to further clarify if needed.

**Comment by NicholasG04** [comment]
Please explain why this is necessary when there are a plethora of other bots out there that do this extremely well.

**Comment by JoshHeng** [comment]
You could also add temp banning and maybe storing user roles in a db so if they leave and join again their roles persist

**Comment by H4ckerJ4cker** [comment]
@NicholasG04 Why cook your own meals when you can buy ready meals which are easier. You do it because it is better for you, and in this case it looks better.

**Comment by NicholasG04** [comment]
uh this is a case where I would argue it's a michelin star chef against your home cooking. I know which one I'd pick.

**Comment by H4ckerJ4cker** [comment]
Where should we store banned words?

**Comment by Bentechy66** [comment]
> Where should we store banned words?

Store them in a database, if you put them in a file and that file gets changed it won't persist thanks to beanos cloud madness

**Comment by NicholasG04** [comment]
Store them in a file, don't use Beano's cloud madness!

**Comment by Bentechy66** [comment]
> Store them in a file, don't use Beano's cloud madness!

Agree, please convince beano to cease the cloud madness

**Comment by JoshHeng** [comment]
> 
> 
> > Where should we store banned words?
> 
> Store them in a database, if you put them in a file and that file gets changed it won't persist thanks to beanos cloud madness

You'll also be able to dynamically change the words with commands/the webpanel if it gets implemented.. but it might be overcomplicating it. A file would probably suffice
