### ISSUE TITLE
Vote Off Quotes

### ISSUE THREAD

**Issue by thebeanogamer** [CyberDiscovery/cyberdisc-bot#345]
Some quotes are bad and there should be a way for users to remove them. I was thinking a 10 minute window after a quote is posted where users with the Quote Czar role can vote to remove a quote and if a threshold it is removed (maybe with logging?).

**Comment by JX-CW** [comment]
I think this is a great idea. Perhaps we can add a STFU emote which will delete a quote when it gets 10.

**Comment by Bottersnike** [comment]
I think this'd be a pretty neat idea. As the number of Quote Czars has been increasing, so has the frequency of just generally not-funny quotes. 10 minutes might be a bit short? I'd imagine the threshold would want to be sufficiently high that there's a clear consensus (5?), and I'm not sure if 10 minutes would be long enough for enough people to notice it and also deem it bad enough to remove.

**Comment by AlphexGaming** [comment]
This does seem like a really good idea. One extra feature could be the person being quoted would potentially be allowed to veto the addition of the quote by reacting  a certain emoji. This would help prevent out of context quotes they are not conformable with from being added

**Comment by ZomBMage** [comment]
Yeah, this seems really nice!

**Comment by picapi** [comment]
> This does seem like a really good idea. One extra feature could be the person being quoted would potentially be allowed to veto the addition of the quote by reacting a certain emoji. This would help prevent out of context quotes they are not conformable with from being added

I second this - and think if possible there shouldn't be a restriction on the timeframe for this,
quotes are meant to be a bit of fun but if the person involved isn't happy with it; it kinda turns into something else less fun I guess
