### ISSUE TITLE
Quote deletion logging

### ISSUE THREAD

**Issue by thebeanogamer** [CyberDiscovery/cyberdisc-bot#359]
Including who voted

**Comment by H4ckerJ4cker** [comment]
Could you give some more information on how you want this to work. Do you want to replace a deleted quote with: “quote voted to be deleted by [list of users]” Or just [last user that voted before deletion] or do you just want to collate the data of who is downvoting quotes most?

**Comment by thebeanogamer** [comment]
An embed with the quote and a list of the people who voted it off would be perfect

**Comment by thebeanogamer** [comment]
In #log

**Comment by Bentechy66** [comment]
#developer-log***

**Comment by H4ckerJ4cker** [comment]
Ah I see, I wasn’t sure if this was a staff thing or a public thing, thanks for the clarification.
