### ISSUE TITLE
Cheesing the downvote feature

### ISSUE THREAD

**Issue by AnonGuy** [CyberDiscovery/cyberdisc-bot#373]
It's currently possible to prevent downvotes by filling up the emoji list for a message in #quotes. Maybe we should add a bot listener for `on_reaction_add` which adds a downvote prematurely?

**Comment by thebeanogamer** [comment]
I smell a boundary test

**Comment by H4ckerJ4cker** [comment]
Is it maybe a good idea to have the bot react with a thumbs up and a thumbs down as soon as a quote is sent. This would fix the problem where people who maybe aren't very active or are new to the server don't know you can even downvote quotes. Maybe we should even change the emoji to a down arrow and an up arrow to make it more clear what it's for.

**Comment by thebeanogamer** [comment]
I'm not totally sure we need a 👍, but at least in the case of 👎  I'd argue that it works because it's a very obvious expression of a negative emotion.
