### ISSUE TITLE
Flake8 Ignores

### ISSUE THREAD

**Issue by thebeanogamer** [CyberDiscovery/cyberdisc-bot#390]
We ignore far too many flake8 errors, mostly because they don't support Python 3.8 and the Walrus.

Once flake8 supports this, we should remove the ignores.

**Comment by Sh3llcod3** [comment]
I agree, let's remove everything to do with flake8, all configs, outputs, etc. Then add it back to the TOML, but use an "*" for versioning, since we really aren't to concerned about pinning the version for a linter.
