### ISSUE TITLE
Can we remove the Kali 🚔 react?

### ISSUE THREAD

**Issue by clubby789** [CyberDiscovery/cyberdisc-bot#411]
**Is your feature request related to a problem? Please describe.**
It just gets kind of spammy when people are trying to discuss Kali and half the screen is 🚔

**Describe the solution you'd like**
No more reacts to Kali

**Comment by AnonGuy** [comment]
no

**Comment by thebeanogamer** [comment]
Rude tbh @AnonGuy

**Comment by lightspeedana** [comment]
"NO, no stop bad" - beano 2020
