### ISSUE TITLE
Automate Readme Deployment

### ISSUE THREAD

**Issue by thebeanogamer** [CyberDiscovery/cyberdisc-bot#413]
**Is your feature request related to a problem? Please describe.**
The current #readme deployment commands are fiddly and no one really knows how to use them.

**Describe the solution you'd like**
When the bot boots, it should check if there have been changes to `readme.json` then deploy if there have been. We should probably add some validation though rather than just checking Git, as if the bot reboots and the most recent commit changes #readme, it will redeploy when it doesn't need to.

**Describe alternatives you've considered**
We don't update #readme very often, so we could just leave it as is.

**Comment by thebeanogamer** [comment]
Also, the current commands don't nuke #readme, we do that manually. Should probably fix that.

**Comment by Sh3llcod3** [comment]
I can make it nuke the channel before sending, if that's what you want.

For auto-deploy, I could look into it, validation is easy enough, just take a sha256 of the file and compare against a value written to disk before.

**Comment by thebeanogamer** [comment]
> I can make it nuke the channel before sending, if that's what you want.

This would be a good start.

> just take a sha256 of the file and compare against a value written to disk before

Remember that we don't have persistent disk.
