### ISSUE TITLE
Maths Abuse Protection

### ISSUE THREAD

**Issue by thebeanogamer** [CyberDiscovery/cyberdisc-bot#429]
The LaTeX commands probably needs all of these.

* Rate limiting (user, channel, overall buckets)
* Limit the number of equations in a message
* Lock down which channels it can be used in.

**Comment by picapi** [comment]
The second bullet point here is somewhat addressed in #430; however may warrant further amendment.

**Comment by picapi** [comment]
Additional changes to this effect have been included in #437, with more presumably to come.

-

**Comment by thebeanogamer** [comment]
I think we've done as much as this needs, we can re-open if it becomes a problem again.
