### ISSUE TITLE
Revive triggering “no” response triggering in the wrong context

### ISSUE THREAD

**Issue by NateKomodo** [CyberDiscovery/cyberdisc-bot#43]
I was discussing the ReVive SDK and the bot was spamming “No” like nobodies business, add a context check eg. message is one word long

**Comment by BurnoutBen** [comment]
@NateKomodo it happens with all the trigger words. Type something like 'blah blah blah kali yeet' and it adds a police car. I could change the code so it has to be one word for the revive one?

**Comment by AnonGuy** [comment]
Might be a good idea to implement simple regex patterns for the trigger words, rather than using substrings.
For example:
```regex
^revive$
```
```regex
\bkali\b
```
