### ISSUE TITLE
Adding a purge-from command, allowing all messages after a given message ID to be purged.

### ISSUE THREAD

**Issue by picapi** [CyberDiscovery/cyberdisc-bot#44]
Sometimes, discussion can get a little out of hand, and needs to be wiped from the face of the earth, however often it can take multiple tries to do, as the number of messages needs to be guesstimated in order to successfully rid the server of the discussion.

An command, for example purgeFrom, that would allow a message ID to be defined, and then all messages chronologically after the referenced message to then be wiped from the channel, would solve the issue of having to issue multiple purge commands, saving the chat window from having to be reloaded a second time.

**Comment by SolitudalDeveloper** [comment]
https://github.com/CyberDiscovery/cyberdisc-bot/pull/45

**Comment by AnonGuy** [comment]
I've closed #45, since there's no sign of @SolitudalDeveloper fixing their build tests, or giving any valid reason for continuing that PR at all. This issue is still open, feel free to make a PR for it.
