### ISSUE TITLE
Send a cheating video if someone does :flag (or on a regex match)

### ISSUE THREAD

**Issue by JoshHeng** [CyberDiscovery/cyberdisc-bot#481]
We've just found a CD cheating video that pops up on a duplicate flag.
Send a link to this in addition to the random string on the `:flag` command, and maybe add it if a message contains the words `flag` and `sell`, or something similar.
A command could also be added to return this (such as `!cheating`)

Video link:
https://game.joincyberdiscovery.com/assets/videos/cheating_message.mp4

**Comment by thebeanogamer** [comment]
Maybe every one in 5 uses of `:flag` sends the video instead?

**Comment by thebeanogamer** [comment]
Resolved by #489
