### ISSUE TITLE
Make CD Bot great again :blobstriker:

### ISSUE THREAD

**Issue by woaisthisgit** [CyberDiscovery/cyberdisc-bot#487]
This entails banning Jack from ever contributing to the CD Bot ever again.

I don't have concrete proof it's his fault, but ever since JackerHacker started writing "code" for the CD Bot it's been scuffed as fuck. Quotes have been broken a total of 3 times now. These _could_ be not all his fault, but realistically? They probably are. If only Jack had done any basic testing he would've realised that no, his code doesn't work, and also it just sucks in general.
```python
if len(list(filter(lambda m: check(m), self.client.cached_messages))) >= 4:
```
What on earth is that? Creating a lambda, that takes in a value, passes it to a function, and returns the returned value... you're just wrapping the function in the lambda for no reason. 

In order to protect our beloved bot urgent action is needed right now. I hope the mods can see the logic in what I'm saying here, and take the reasonable and moral course of action ASAP.

**Comment by Bottersnike** [comment]
This is not the attitude we want to be promoting here. Constructive criticism is better placed in a code review, and unconstructive criticism has no place here at all.

**Comment by thebeanogamer** [comment]
Not helpful.
