### ISSUE TITLE
Quotes borked pls fix

### ISSUE THREAD

**Issue by woaisthisgit** [CyberDiscovery/cyberdisc-bot#511]
I'm sure you already know this but quotes aren't getting deleted if they have 10 or more downvotes. I'm going to try to fix this but in the meantime could a mod please moderate and delete these 10 or so messages? Cheers x

https://discord.com/channels/409851296116375565/463657120441696256/735923474710790295
https://discord.com/channels/409851296116375565/463657120441696256/736356554512793613
https://discord.com/channels/409851296116375565/463657120441696256/738068849483710585
https://discord.com/channels/409851296116375565/463657120441696256/738335433875783751
https://discord.com/channels/409851296116375565/463657120441696256/739439081435431002
https://discord.com/channels/409851296116375565/463657120441696256/739605026795683912
https://discord.com/channels/409851296116375565/463657120441696256/739776369319346256
https://discord.com/channels/409851296116375565/463657120441696256/739844938942120047
https://discord.com/channels/409851296116375565/463657120441696256/739961021187489914
https://discord.com/channels/409851296116375565/463657120441696256/735072879259156493

**Comment by Alpheeexx** [comment]
Messages have been deleted 👍 . Now where's the pr :)

**Comment by woaisthisgit** [comment]
:ummmmmm:

**Comment by thebeanogamer** [comment]
Duplicate of #518

**Comment by woaisthisgit** [comment]
mine was first beanolamer, you're the duplicate
