### ISSUE TITLE
README provides incorrect version of python for installation

### ISSUE THREAD

**Issue by 404dcd** [CyberDiscovery/cyberdisc-bot#525]
[Line 52](https://github.com/CyberDiscovery/cyberdisc-bot/blame/master/README.md#L52) of README.md advises me to use python 3.7.2, but looks like the bot runs on python 3.8+.
![image](https://user-images.githubusercontent.com/46684921/91963980-7fec4a00-ed06-11ea-8137-cfb612a31cd3.png)

**Comment by H4ckerJ4cker** [comment]
Yes this needs updated.

**Comment by thebeanogamer** [comment]
This is a good point, it should work on 3.7, but Poetry insists 3.8 for consistency. We should update the readme, I'm in my phone so if someone else makes the PR I'll approve it
