### ISSUE TITLE
make welcome message better

### ISSUE THREAD

**Issue by KyokoKirigiri11037** [CyberDiscovery/cyberdisc-bot#561]
**Is your feature request related to a problem? Please describe.**
yes, the welcome message currently reads shit and needs to be better

**Describe the solution you'd like**
make the welcome message better

**Describe alternatives you've considered**
deleteing the cd server but beano is unresponsive to anybody asking him to do his fucking job

**Additional context**
ez pz

**Comment by 404dcd** [comment]
I say we change it to `<user mention>, Welcome to the Cyber Discovery discussion discord! Before you begin, please check the rules and information in #readme.`
