### ISSUE TITLE
Leave messages don't work

### ISSUE THREAD

**Issue by david-cooke** [CyberDiscovery/cyberdisc-bot#568]
**Describe the bug**
You broke leave messages

**To Reproduce**
Leave the server

**Expected behavior**
It should send a leave message

**Additional context**
This has caused me great amounts of distress as I regularly leave the server and not having the leave message send because someone wanted a free tshirt greatly increases the complexity of communicating that I am no longer in the server.

**Comment by H4ckerJ4cker** [comment]
I'll look into this, was working fine for a few days i believe.

**Comment by H4ckerJ4cker** [comment]
Code works fine locally

**Comment by 404dcd** [comment]
That's why I think it was beano when he updated everything. #567

**Comment by H4ckerJ4cker** [comment]
found the bug, Discord API changed. Patch coming soon :)
