### ISSUE TITLE
welcome messages are no more

### ISSUE THREAD

**Issue by KyokoKirigiri11037** [CyberDiscovery/cyberdisc-bot#572]
**Describe the bug**
Welcome messages are proper fucked lads

**To Reproduce**
join the server and there is fuck all sent

**Expected behavior**
join the server and get a nice welcome message that someone just fixed

**Screenshots**
is hentai acceptable here? Asking for rak of course

**Additional context**
works locally apparently but idk i dont code this dumpster fire that is a discord bot

**Comment by H4ckerJ4cker** [comment]
yeah I can confirm it works fine on my test bot

**Comment by H4ckerJ4cker** [comment]
found the bug, Discord API changed. Patch coming soon :)
