### ISSUE TITLE
Change prefix to something other than :

### ISSUE THREAD

**Issue by H4ckerJ4cker** [CyberDiscovery/cyberdisc-bot#591]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I try to invoke a command and it gets replaced with an emoji. Any command with a name similar to emoji gets replaced unless you add an extra space.

**Describe the solution you'd like**
We could use something like $ or /

**Describe alternatives you've considered**
Maybe even % or ! if we change mee6 to something else

**Comment by JoshHeng** [comment]
`/` is also the prefix for Discord's native commands - don't know if that makes a difference or not

I would recommend `?` but other symbols like `= / + / -` can also be used

**Comment by H4ckerJ4cker** [comment]
/ shouldn't be too much of a problem there's not many native commands but anything other than :

**Comment by AryanBeezadhur** [comment]
I would prefer `.`
