### ISSUE TITLE
quote database bug with mentions

### ISSUE THREAD

**Issue by H4ckerJ4cker** [CyberDiscovery/cyberdisc-bot#596]
**Describe the bug**
When a quote is added to the database from the mentions criteria it will only add the quote to the first mentioned person's quotes

**To Reproduce**
1. use 2 mentions in a image quote

**Expected behavior**
the quote is added to both mentions quotes up to a limit.

**Additional context**
Small bug, may not even be worth fixing. The bug originates from line 498 in cogs/fun.py

**Comment by thebeanogamer** [comment]
Fastest solution is probably to loop the DB add for each mention
