### ISSUE TITLE
Minecraft Server command

### ISSUE THREAD

**Issue by 404dcd** [CyberDiscovery/cyberdisc-bot#602]
**Is your feature request related to a problem? Please describe.**
I think it would be good if we made an :mcserver or :server command to report on the status of the minecraft server

**Describe the solution you'd like**
Command reports player count, maybe player names, version, up/not up ....

**Describe alternatives you've considered**
There is no alternative

**Additional context**
none required

**Comment by 404dcd** [comment]
I am happy to work on this also

**Comment by H4ckerJ4cker** [comment]
too late bro
