### ISSUE TITLE
Way too many PRs open for way too long

### ISSUE THREAD

**Issue by 404dcd** [CyberDiscovery/cyberdisc-bot#607]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I come to work on the bot and see about 10 different PRs open that make massive changes to the code and add various new commands. This makes it hard to work on code because I don't know if the feature I'm adding is going to be overwritten by an already outstanding PR.

**Describe the solution you'd like**
Could the root team just hurry up and approve them??

**Describe alternatives you've considered**
Idk just approve the PRs please

**Additional context**
@thebeanogamer @Trefonix

**Comment by thebeanogamer** [comment]
But all the PRs are by @H4ckerJ4cker, and I'm scared of merging his code

**Comment by H4ckerJ4cker** [comment]
Merge #574
Do it
