### ISSUE TITLE
Base 64 function is incorrectly returning base 65

### ISSUE THREAD

**Issue by 404dcd** [CyberDiscovery/cyberdisc-bot#608]
**Describe the bug**
When the bot generates a fake flag, it calls a generatebase64 function. https://github.com/CyberDiscovery/cyberdisc-bot/blob/3b1502f77f9413510c2062b58136cd787d72b770/cdbot/cogs/cyber.py#L32
This can return 0-9 digits, upper and lower ascii chars, +, / and =. This is in total 10+26+26+3 = 65 char options.

**To Reproduce**
Look at the function

**Expected behavior**
The = character not to be included in the letters it chooses

I'll get a PR out within about 3 minutes

**Comment by thebeanogamer** [comment]
Resolved by #609
