### ISSUE TITLE
Make The Staff Hate Us Less

### ISSUE THREAD

**Issue by thebeanogamer** [CyberDiscovery/cyberdisc-bot#64]
**Is your feature request related to a problem? Please describe.**
The staff keep getting annoyed with us for tagging them.

**Describe the solution you'd like**
When the Staff role is tagged, the bot should repond with `Have you tried emailing support@joincyberdiscovery.com? Please make sure to do that before unnecessarily pinging the staff!`. It could also respond to if the staff are individually tagged, but this would require a cooldown to prevent spam.

**Describe alternatives you've considered**
Screaming at people to stop doing it.

**Additional context**
To help with development, here are some IDs:
`Official Cyber Discovery Staff: 510507184396959785`
`@ampersand#3620: 453547861888598018`
`@Flex#0394: 474332857783943169`
`@Hlant#2066: 499567665774329859`
`@jibhat#1294: 453547861888598018`

**Comment by thebeanogamer** [comment]
This is something the staff have specifically requested: 
![image](https://user-images.githubusercontent.com/3729048/48278885-bf1d1d00-e446-11e8-8a89-631d3d47f567.png)

**Comment by AnonGuy** [comment]
After some discussion, we've come up with some possible solutions:

- [ ] **Create a fake, pingable staff role to lure help vampires**
Follow the fake ping with a message like "Have you tried emailing support?"

- [ ] **Discourage users from pinging staff individually**
Maybe this could be done by sending a similar message, or muting users who abuse staff pings?

**Comment by thebeanogamer** [comment]
With Game coming up, this needs to be urgently resolved. Personally, my prefered solution is #79, although I guess that #65 would probably also work.

If someone is able to test #79 and confirm that it works, then I think it's good to merge.

**Comment by AnonGuy** [comment]
I'll be making a PR for this tonight, since #79 has been inactive for a while.

**Comment by teamshortcut** [comment]
👀
