### ISSUE TITLE
When using the 'assess' command, should the challenge be linked (or include an image)?

### ISSUE THREAD

**Issue by joker314** [CyberDiscovery/cyberdisc-bot#72]
#### Is your feature request related to a problem? Please describe.
When viewing a challenge using the `:assess <number>` command, the output only provides the text content describing the challenge, but the challenge itself is very useful in identifying how it was solved.

#### Describe the solution you'd like
Make the title of the Discord embed a hyperlink to the challenge. The problem with this is that if the user isn't logged in, you get a 404 page.

Because of the design of Cyber Discovery, this 404 page is not massively helpful, because after logging in, you don't get redirected to the challenge you're looking for.

Could this hyperlinking idea be combined with the image idea explained below, to make it useful to people who are logged in and also people who aren't?

#### Describe alternatives you've considered
- Allow the user to find the challenge themselves
- **Display an image (screenshot) of the challenge**
- Link to the log-in page

**Comment by AnonGuy** [comment]
This was resolved by #74.
