### ISSUE TITLE
Username changes result in previous quotes not being accessible

### ISSUE THREAD

**Issue by fractalpenguin** [CyberDiscovery/cyberdisc-bot#80]
**Describe the bug**
Nickname changes cause the quotes function to not retrieve all quotes

**To Reproduce**
1. Quote a message
2. Change nickname
3. View quotes

**Expected behavior**
All quotes shown. Instead, none shown.

**Additional context**
Could be detected via discriminator, but Nitro users would break that as well.

**Comment by justanotherfailure** [comment]
This won't be able to be fixed easily without storing the quotes locally along with user (basically breaking a lot of the old quotes) or rebuilding a custom quotes system from scratch.
