### ISSUE TITLE
Put Docker In The Readme

### ISSUE THREAD

**Issue by thebeanogamer** [CyberDiscovery/cyberdisc-bot#81]
**Is your feature request related to a problem? Please describe.**
The `README.md` file should include the use of the Dockerfile, and it should be the prefered option.

**Describe the solution you'd like**
In the `README.md` file, include the commands to build and run the Docker container.

**Comment by fractalpenguin** [comment]
For development, pipenv is the better option: The Docker container method is more suitable for deployment.

**Comment by AnonGuy** [comment]
I agree with @fractalpenguin - we already mention pipenv in the README, which is ideal for local development.
