### ISSUE TITLE
Increase maintainability by keeping dates in e.g. env variables, et cetera

### ISSUE THREAD

**Issue by joker314** [CyberDiscovery/cyberdisc-bot#85]
The dates of the stages of competitions (assess, game, essentials, elite) change annually.

To keep the code more maintainable:
- store the dates in environment variables, or at least in a JSON file.
- have the bot automatically determined which stage is active and hence which command to respond to or similar

This is a low priority ergonomics issue

**Comment by swedg** [comment]
Wait, the repo wasn't already like this? Who do I have to shout at :rage:
Jokes aside, yeah ima +1 this

**Comment by AnonGuy** [comment]
This is on hold until we figure out the CI business.
